export type Role = 'superadmin' | 'admin' | 'staff' | 'limited' | 'customer'

const roleAccess: Record<Role, string[]> = {
  superadmin: [
    'dev',
    'logs',
    'inventory',
    'inventorySettings',
    'claims',
    'media',
    'dashboard',
    'chat',
    'analytics',
    'broadcast',
    'collections',
    'reviews',
    'supply',
    'unpaid',
    'faq',
    'feedback',
    'campaigns',
    'fastBills',
    'users',
  ],
  admin: [
    'dev',
    'logs',
    'inventory',
    'inventorySettings',
    'claims',
    'media',
    'dashboard',
    'chat',
    'analytics',
    'broadcast',
    'collections',
    'reviews',
    'supply',
    'unpaid',
    'faq',
    'feedback',
    'campaigns',
    'fastBills',
    'users',
  ],
  staff: [
    'inventory',
    'claims',
    'media',
    'dashboard',
    'chat',
    'analytics',
    'broadcast',
    'collections',
    'reviews',
    'supply',
    'unpaid',
    'faq',
    'feedback',
    'campaigns',
    'fastBills',
    'users',
  ],
  limited: ['dashboard', 'chat'],
  customer: [],
}

export function canAccess(role: Role | undefined, feature: string): boolean {
  if (!role) return false
  return roleAccess[role].includes(feature)
}
